.TH "config_reader" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_reader
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigReader\fP"
.br
.RI "Main class is \fBconfig_reader\fP The class is for reading the values of the image\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetDistance\fP (self)"
.br
.RI "The class is used to retrieve the distance between the projectors\&. "
.ti -1c
.RI "def \fBgetWidth\fP (self)"
.br
.RI "The class is used to retrieve width of the image being projected on the screen\&. "
.ti -1c
.RI "def \fBgetIMGWidth\fP (self)"
.br
.RI "The class is used to retrieve the actual width value of the image( how many pixels is the iamge width comprised of) "
.ti -1c
.RI "def \fBgetIMGHeight\fP (self)"
.br
.RI "The class is used to retrieve the actual height value of the image( how many pixels is the iamge height comprised of) "
.ti -1c
.RI "def \fBgetIMGName\fP (self)"
.br
.RI "The class is used to retrieve the name of the image ( assigned string value of the image name variable) "
.ti -1c
.RI "def \fBgetGamma\fP (self)"
.br
.RI "The class is used to retrieve the gamma value of image, used for gamma correction\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def config_reader\&.getDistance ( self)"

.PP
The class is used to retrieve the distance between the projectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIself\fP is the object pointer, points to the class itself 
.RE
.PP

.PP
Definition at line 24 of file config_reader\&.py\&.
.SS "def config_reader\&.getGamma ( self)"

.PP
The class is used to retrieve the gamma value of image, used for gamma correction\&. 
.PP
\fBParameters\fP
.RS 4
\fIself\fP is the object pointer, points to the class itself 
.RE
.PP

.PP
Definition at line 49 of file config_reader\&.py\&.
.SS "def config_reader\&.getIMGHeight ( self)"

.PP
The class is used to retrieve the actual height value of the image( how many pixels is the iamge height comprised of) 
.PP
\fBParameters\fP
.RS 4
\fIself\fP is the object pointer, points to the class itself 
.RE
.PP

.PP
Definition at line 39 of file config_reader\&.py\&.
.SS "def config_reader\&.getIMGName ( self)"

.PP
The class is used to retrieve the name of the image ( assigned string value of the image name variable) 
.PP
\fBParameters\fP
.RS 4
\fIself\fP is the object pointer, points to the class itself 
.RE
.PP

.PP
Definition at line 44 of file config_reader\&.py\&.
.SS "def config_reader\&.getIMGWidth ( self)"

.PP
The class is used to retrieve the actual width value of the image( how many pixels is the iamge width comprised of) 
.PP
\fBParameters\fP
.RS 4
\fIself\fP is the object pointer, points to the class itself 
.RE
.PP

.PP
Definition at line 34 of file config_reader\&.py\&.
.SS "def config_reader\&.getWidth ( self)"

.PP
The class is used to retrieve width of the image being projected on the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIself\fP is the object pointer, points to the class itself 
.RE
.PP

.PP
Definition at line 29 of file config_reader\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
