.TH "config_reader.ConfigReader" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_reader.ConfigReader \- Main class is \fBconfig_reader\fP The class is for reading the values of the image\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, filename)"
.br
.RI "main class The constructor, defining all the methods of the main class(configure values of the image) "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main class is \fBconfig_reader\fP The class is for reading the values of the image\&. 
.PP
Definition at line 13 of file config_reader\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def config_reader\&.ConfigReader\&.__init__ ( self,  filename)"

.PP
main class The constructor, defining all the methods of the main class(configure values of the image) 
.PP
\fBParameters\fP
.RS 4
\fIself\fP object pointer 
.RE
.PP

.PP
Definition at line 18 of file config_reader\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "config_reader\&.ConfigReader\&.config"

.PP
Definition at line 19 of file config_reader\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
