.TH "config_reader.py" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_reader.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconfig_reader\&.ConfigReader\fP"
.br
.RI "Main class is \fBconfig_reader\fP The class is for reading the values of the image\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconfig_reader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconfig_reader\&.getDistance\fP (self)"
.br
.RI "The class is used to retrieve the distance between the projectors\&. "
.ti -1c
.RI "def \fBconfig_reader\&.getWidth\fP (self)"
.br
.RI "The class is used to retrieve width of the image being projected on the screen\&. "
.ti -1c
.RI "def \fBconfig_reader\&.getIMGWidth\fP (self)"
.br
.RI "The class is used to retrieve the actual width value of the image( how many pixels is the iamge width comprised of) "
.ti -1c
.RI "def \fBconfig_reader\&.getIMGHeight\fP (self)"
.br
.RI "The class is used to retrieve the actual height value of the image( how many pixels is the iamge height comprised of) "
.ti -1c
.RI "def \fBconfig_reader\&.getIMGName\fP (self)"
.br
.RI "The class is used to retrieve the name of the image ( assigned string value of the image name variable) "
.ti -1c
.RI "def \fBconfig_reader\&.getGamma\fP (self)"
.br
.RI "The class is used to retrieve the gamma value of image, used for gamma correction\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
