.TH "image_rw.ImageRW" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
image_rw.ImageRW \- The main class \fBImageRW\fP The class is for reading and writing the image, reading in image values and writing in new values to variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.RI "main class The constructor, defining all the methods of the main class "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBimg_width\fP"
.br
.ti -1c
.RI "\fBimg_height\fP"
.br
.ti -1c
.RI "\fBdistance\fP"
.br
.ti -1c
.RI "\fBprojector\fP"
.br
.ti -1c
.RI "\fBoriginalImage\fP"
.br
.ti -1c
.RI "\fBmaskArea\fP"
.br
.ti -1c
.RI "\fBgammaRate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main class \fBImageRW\fP The class is for reading and writing the image, reading in image values and writing in new values to variables\&. 
.PP
Definition at line 18 of file image_rw\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def image_rw\&.ImageRW\&.__init__ ( self)"

.PP
main class The constructor, defining all the methods of the main class 
.PP
\fBParameters\fP
.RS 4
\fIself\fP object pointer 
.RE
.PP

.PP
Definition at line 23 of file image_rw\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "image_rw\&.ImageRW\&.distance"

.PP
Definition at line 28 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.filename"

.PP
Definition at line 25 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.gammaRate"

.PP
Definition at line 32 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.img_height"

.PP
Definition at line 27 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.img_width"

.PP
Definition at line 26 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.maskArea"

.PP
Definition at line 31 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.originalImage"

.PP
Definition at line 30 of file image_rw\&.py\&.
.SS "image_rw\&.ImageRW\&.projector"

.PP
Definition at line 29 of file image_rw\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
