.TH "main_stitcher.MainStitcher" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_stitcher.MainStitcher \- Documentation for main class \fBMainStitcher\fP The constructor, used to stitch together the divided parts of the original image, returns the final image at the end of the class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBstitchImage\fP (self, leftPart, rightPart)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Documentation for main class \fBMainStitcher\fP The constructor, used to stitch together the divided parts of the original image, returns the final image at the end of the class\&. 

Documentation for the class stitchImage this class is to stitch together the left and right parts of the image after being divided, and form a final image 
.PP
Definition at line 14 of file main_stitcher\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def main_stitcher\&.MainStitcher\&.stitchImage ( self,  leftPart,  rightPart)"

.PP
Definition at line 16 of file main_stitcher\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
