.TH "main_stitcher" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_stitcher
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainStitcher\fP"
.br
.RI "Documentation for main class \fBMainStitcher\fP The constructor, used to stitch together the divided parts of the original image, returns the final image at the end of the class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDisplay\fP (self, finalLeft, finalRight)"
.br
.RI "Documentation for the class Display used to display the final image after being finished\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def main_stitcher\&.Display ( self,  finalLeft,  finalRight)"

.PP
Documentation for the class Display used to display the final image after being finished\&. 
.PP
Definition at line 24 of file main_stitcher\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
