.TH "main_stitcher.py" 3 "Thu Jan 7 2021" "G12 PBL 4 project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_stitcher.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmain_stitcher\&.MainStitcher\fP"
.br
.RI "Documentation for main class \fBMainStitcher\fP The constructor, used to stitch together the divided parts of the original image, returns the final image at the end of the class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmain_stitcher\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain_stitcher\&.Display\fP (self, finalLeft, finalRight)"
.br
.RI "Documentation for the class Display used to display the final image after being finished\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for G12 PBL 4 project from the source code\&.
